DROP SCHEMA if exists VACINA_ANIMAL;

CREATE SCHEMA VACINA_ANIMAL;

USE VACINA_ANIMAL;

CREATE TABLE USUARIOS (
    ID_USUARIO INT(20) AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(15) UNIQUE NOT NULL,
    SENHA VARCHAR(32) NOT NULL,
    STATUS_USUARIO BOOLEAN NOT NULL
);

CREATE TABLE ANIMAL (
    ID_ANIMAL INT(20) AUTO_INCREMENT PRIMARY KEY,
    NR_BRINCO INT(20) UNIQUE NOT NULL,
    FZND_ORIGEM VARCHAR(15),
	DT_NASCIMENTO VARCHAR(10),
    OBS_ANIMAL VARCHAR(150),
    SEXO VARCHAR(10),
    RACA VARCHAR (15)
);

CREATE TABLE HISTORICO_MEDICOES (
	ID_MEDICAO INT(20) AUTO_INCREMENT PRIMARY KEY,
	PESO_MEDICAO FLOAT(10),
    DATA_MEDICAO DATE,
    OBS_MEDICAO VARCHAR(150),
	ID_ANIMAL INT(20)
);

CREATE TABLE VACINA (
    ID_VACINA INT(20) AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO_VACINA VARCHAR(50),
    QTD_ATUAL INT(8),
    QTD_MINIMA INT(8),
    OBS_VACINA VARCHAR(150),
    DT_VALIDADE VARCHAR(10),
	LOTE VARCHAR(15),
    CUSTO INT(5),
    FABRICANTE VARCHAR(25),
    STATUS_VACINA BOOLEAN
);

CREATE TABLE VACINACAO (
    ID_VACINACAO INT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_ANIMAL INT(20) NOT NULL,
    ID_VACINA INT(20) NOT NULL,
    DATA_VACINACAO DATE,
    DOSES_VACINACAO INT(3),
    OBS_VACINACAO VARCHAR(150)
);

ALTER TABLE HISTORICO_MEDICOES ADD FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL(ID_ANIMAL);

ALTER TABLE VACINACAO ADD FOREIGN KEY (ID_VACINA) REFERENCES VACINA(ID_VACINA);
ALTER TABLE VACINACAO ADD FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL(ID_ANIMAL);

INSERT INTO USUARIOS (LOGIN, SENHA, STATUS_USUARIO) VALUES
('ADMIN', 'admin', TRUE);

INSERT INTO VACINA (DESCRICAO_VACINA, QTD_MINIMA, QTD_ATUAL, DT_VALIDADE, OBS_VACINA, LOTE, CUSTO, FABRICANTE) VALUES
('FORTRESS 7 VACINA - 50ml',1,5,'2018-12-31','Bacterina Toxóide contra Carbúnculo Sintomático, Gangrena Gasosa e Enterotoxemia dos Bovinos.','123456',250,'ZOETIS - PFIZER'),
('LINOVAC - 100ml',1,5,'2018-12-31','Vacina aquosa, inativada, contra o botulismo dos bovinos, ovinos, caprinos e eqüinos.','123456',250,'MERIAL'),
('BIOLEPTOGEN - 125ml',1,5,'2018-12-31','Vacina contra a Leptospirose Bovina e Suína','123456',250,'BIOGENESIS'),
('RAI-VET LÍQUIDA VACINA - 50ml',1,5,'2018-12-31','Vacina inativada contra raiva dos herbívoros.','123456',250,'BIOVET'),
('OUROVAC AFTOSA -50ml',1,5,'2018-12-31','Vacina bivalente contra a febre aftosa.','123456',250,'OUROCAC');


INSERT INTO ANIMAL (NR_BRINCO, FZND_ORIGEM, DT_NASCIMENTO, OBS_ANIMAL, SEXO, RACA) VALUES
(01,'FAZENDA A','2018-01-01','Animal saudável','M', 'ANGUS'),
(02,'FAZENDA A','2018-01-01','Animal saudável','M', 'ANGUS'),
(03,'FAZENDA A','2018-01-01','Animal saudável','M', 'ANGUS'),
(04,'FAZENDA A','2018-01-01','Animal abaixo do peso','M', 'SIMENTAL'),
(05,'FAZENDA A','2018-01-01','Animal abaixo do peso','M', 'SIMENTAL'),
(06,'FAZENDA B','2017-05-16','Animal abaixo do peso','M', 'BRAFORD'),
(07,'FAZENDA B','2017-05-16','Animal saudável','M', 'ANGUS'),
(08,'FAZENDA B','2017-01-10','Animal saudável','M', 'ANGUS'),
(09,'FAZENDA B','2017-02-11','Animal saudável','M', 'SIMENTAL'),
(10,'FAZENDA B','2017-03-03','Animal saudável','M', 'BRAFORD');

CREATE USER 'gaersys'@'localhost' IDENTIFIED BY 'gaerpass';
GRANT ALL PRIVILEGES ON VACINA_ANIMAL.* TO 'gaersys'@'localhost';
FLUSH PRIVILEGES;